version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - /mnt/uvdeskdb:/var/lib/mysql:rw
    restart: always
    environment:
      MYSQL_DATABASE: uvdesk
      MYSQL_ROOT_PASSWORD: M@pagmalasakit
      MYSQL_USER: uvdesk
      MYSQL_PASSWORD: M@pagmalasakit
  uvdesk:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - /mnt/uvdeskapp:/var/www:rw
    depends_on:
      - db
    tty: true
    environment:
        MYSQL_USER: uvdesk
        MYSQL_PASSWORD: M@pagmalasakit
        MYSQL_ROOT_PASSWORD: M@pagmalasakit
        MYSQL_DATABASE: uvdesk
    ports:
        - 80:80
